set_property PACKAGE_PIN T5 [get_ports clk]
set_property PACKAGE_PIN R2 [get_ports ls]
set_property PACKAGE_PIN M4 [get_ports ps]
set_property PACKAGE_PIN N4 [get_ports rs]
set_property PACKAGE_PIN J3 [get_ports ll]
set_property PACKAGE_PIN J2 [get_ports pl]
set_property PACKAGE_PIN K2 [get_ports rl]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports ll]
set_property IOSTANDARD LVCMOS33 [get_ports ls]
set_property IOSTANDARD LVCMOS33 [get_ports pl]
set_property IOSTANDARD LVCMOS33 [get_ports ps]
set_property IOSTANDARD LVCMOS33 [get_ports rs]
set_property IOSTANDARD LVCMOS33 [get_ports rl]

set_property PACKAGE_PIN R1 [get_ports rr]
set_property IOSTANDARD LVCMOS33 [get_ports rr]
